/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: EDB.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @EDB: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@EDB()
	{
		this.StartPassage = "Pet store";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Pet store

	void passage1_Init()
	{
		this.Passages[@"Pet store"] = new StoryPassage(@"Pet store", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("One runs up and puts its nose on the ");
		yield return link("glass", "glass", null);
		yield return text(".");
		yield return lineBreak();
		yield return text("One sits shyly at the back of the ");
		yield return link("pen", "pen", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #2: glass

	void passage2_Init()
	{
		this.Passages[@"glass"] = new StoryPassage(@"glass", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Your puppy is so ");
		yield return link("playful", "playful", null);
		yield return text("!");
		yield return lineBreak();
		yield return text("He is so ");
		yield return link("greedy", "greedy", null);
		yield return text("!");
		yield break;
	}


	// .............
	// #3: morning

	void passage3_Init()
	{
		this.Passages[@"morning"] = new StoryPassage(@"morning", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("He's not ");
		yield return link("eating", "eating", null);
		yield return text(".");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: eating

	void passage4_Init()
	{
		this.Passages[@"eating"] = new StoryPassage(@"eating", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("He's so small when you hold him. You can feel his little heart ");
		yield return link("beating", "beating", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #5: beating

	void passage5_Init()
	{
		this.Passages[@"beating"] = new StoryPassage(@"beating", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Until you can't anymore. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The puppy you chose was sick. ");
		yield return lineBreak();
		yield return text("You go back to the ");
		yield return link("Pet store", "Pet store", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #6: playful

	void passage6_Init()
	{
		this.Passages[@"playful"] = new StoryPassage(@"playful", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("He's whining at the door. Do you: ");
		yield return lineBreak();
		yield return text("Let him ");
		yield return link("out", "out", null);
		yield return text("?");
		yield return lineBreak();
		yield return text("Pick him up and ");
		yield return link("cuddle him", "cuddle him", null);
		yield return text("?");
		yield break;
	}


	// .............
	// #7: greedy

	void passage7_Init()
	{
		this.Passages[@"greedy"] = new StoryPassage(@"greedy", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("He cries when you don't feed him.");
		yield return lineBreak();
		yield return text("Do you:");
		yield return lineBreak();
		yield return text("Keep his bowl ");
		yield return link("full", "full", null);
		yield return text("?");
		yield return lineBreak();
		yield return text("Only feed him twice a ");
		yield return link("day", "day", null);
		yield return text("?");
		yield break;
	}


	// .............
	// #8: out

	void passage8_Init()
	{
		this.Passages[@"out"] = new StoryPassage(@"out", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("He frequently chases the neighbours ");
		yield return link("cat", "cat", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #9: cuddle him

	void passage9_Init()
	{
		this.Passages[@"cuddle him"] = new StoryPassage(@"cuddle him", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Responsible pet owners neuter their dogs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Do you take him to the ");
		yield return link("vet", "vet", null);
		yield return text(" for the snip?");
		yield return lineBreak();
		yield return text("Do you leave him intact? You might want ");
		yield return link("puppies", "puppies", null);
		yield return text(" later!");
		yield break;
	}


	// .............
	// #10: full

	void passage10_Init()
	{
		this.Passages[@"full"] = new StoryPassage(@"full", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("He eats really fast. ");
		yield return lineBreak();
		yield return text("When you hear the sounds from the kitchen, you ");
		yield return link("laugh", "laugh", null);
		yield return text(" at how greedy he is.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: day

	void passage11_Init()
	{
		this.Passages[@"day"] = new StoryPassage(@"day", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("He's always ");
		yield return link("hungry", "hungry", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #12: laugh

	void passage12_Init()
	{
		this.Passages[@"laugh"] = new StoryPassage(@"laugh", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("The soudnds stop.");
		yield return lineBreak();
		yield return text("Everything is too ");
		yield return link("quiet", "quiet", null);
		yield return text(". ");
		yield break;
	}


	// .............
	// #13: quiet

	void passage13_Init()
	{
		this.Passages[@"quiet"] = new StoryPassage(@"quiet", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("You go through to the kitchen.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("His little body is so small...");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You go back to the ");
		yield return link("Pet store", "Pet store", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #14: hungry

	void passage14_Init()
	{
		this.Passages[@"hungry"] = new StoryPassage(@"hungry", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("You fill bowl.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Later", "Later", null);
		yield return text(", his bowl is still full. ");
		yield break;
	}


	// .............
	// #15: Later

	void passage15_Init()
	{
		this.Passages[@"Later"] = new StoryPassage(@"Later", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("You ");
		yield return link("call", "call", null);
		yield return text(" him but he doesn't come.");
		yield break;
	}


	// .............
	// #16: call

	void passage16_Init()
	{
		this.Passages[@"call"] = new StoryPassage(@"call", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("A cupboard is open in the kitchen. The rat poison pellets are spilled across the floor.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("His little body is so small...");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You go back to the ");
		yield return link("Pet store", "Pet store", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #17: pen

	void passage17_Init()
	{
		this.Passages[@"pen"] = new StoryPassage(@"pen", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("He licks your nose. ");
		yield return lineBreak();
		yield return text("His name is:");
		yield return lineBreak();
		yield return link("lucky", "lucky", null);
		yield return text(" because he's going to change your life");
		yield return lineBreak();
		yield return link("fido", "fido", null);
		yield return text(" because he is loyal and brave");
		yield return lineBreak();
		yield return link("buddy", "buddy", null);
		yield return text(" because he's such a good boy");
		yield break;
	}


	// .............
	// #18: lucky

	void passage18_Init()
	{
		this.Passages[@"lucky"] = new StoryPassage(@"lucky", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("The next ");
		yield return link("morning", "morning", null);
		yield return text(" he's right there next to you where you need him to be. ");
		yield break;
	}


	// .............
	// #19: fido

	void passage19_Init()
	{
		this.Passages[@"fido"] = new StoryPassage(@"fido", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("He has such cute puppy ");
		yield return link("morning", "morning", null);
		yield return text(" breath. ");
		yield break;
	}


	// .............
	// #20: buddy

	void passage20_Init()
	{
		this.Passages[@"buddy"] = new StoryPassage(@"buddy", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("He licks your face in the ");
		yield return link("morning", "morning", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #21: cat

	void passage21_Init()
	{
		this.Passages[@"cat"] = new StoryPassage(@"cat", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("You leave the gate open by mistake.");
		yield return lineBreak();
		yield return text("As far as you can tell, he ran out trying to catch the cat.");
		yield return lineBreak();
		yield return text("Does he ");
		yield return link("catch", "catch", null);
		yield return text(" the cat?");
		yield return lineBreak();
		yield return text("Does the cat ");
		yield return link("escape", "escape", null);
		yield return text("?");
		yield break;
	}


	// .............
	// #22: catch

	void passage22_Init()
	{
		this.Passages[@"catch"] = new StoryPassage(@"catch", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("You come home to a note on your door from your neighbour.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"I DID TO YOUR DOG WHAT IT DID TO MY CAT\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You go back to the ");
		yield return link("Pet store", "Pet store", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #23: escape

	void passage23_Init()
	{
		this.Passages[@"escape"] = new StoryPassage(@"escape", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("You come home to a note on your door.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"IM SO SORRY I TRIED TO STOP BUT HE JUST RAN OUT IN FRONT OF MY CAR\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("There's a bloody plastic bag at your feet. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You go back to the ");
		yield return link("Pet store", "Pet store", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #24: vet

	void passage24_Init()
	{
		this.Passages[@"vet"] = new StoryPassage(@"vet", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("Your phone ");
		yield return link("rings", "rings", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #25: puppies

	void passage25_Init()
	{
		this.Passages[@"puppies"] = new StoryPassage(@"puppies", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("He's getting ");
		yield return link("older", "older", null);
		yield return text("!");
		yield break;
	}


	// .............
	// #26: rings

	void passage26_Init()
	{
		this.Passages[@"rings"] = new StoryPassage(@"rings", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("\"It was a routine procedure. I don't know what went wrong.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I'm so sorry.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Go to the ");
		yield return link("Pet store", "Pet store", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #27: older

	void passage27_Init()
	{
		this.Passages[@"older"] = new StoryPassage(@"older", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("He's so ");
		yield return link("boisterous", "boisterous", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #28: boisterous

	void passage28_Init()
	{
		this.Passages[@"boisterous"] = new StoryPassage(@"boisterous", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("He loves playing with his ");
		yield return link("rope", "rope", null);
		yield return text(" toy.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You stroke his little ");
		yield return link("face", "face", null);
		yield return text(" every day.");
		yield break;
	}


	// .............
	// #29: rope

	void passage29_Init()
	{
		this.Passages[@"rope"] = new StoryPassage(@"rope", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #30: face

	void passage30_Init()
	{
		this.Passages[@"face"] = new StoryPassage(@"face", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}